name: pyimp-yaml
on: [push]
jobs:
  install:
  runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: echo "echo command runs"
          #pip3 install pipenv
          #pipenv shell
          #pipenv install
      - name: run main
        run: pipenv run python main.py
