name: pyimp-yaml
on: [push]
jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
    - name: set up python
      # uses: actions/checkout@v2
      uses: actions/setup-python@v2
      with: python-version:3.8

    - name: install dependencies
      # the -m flag means to use the specified python interpreter, here 3.8
      run: |
        python -m pip install --upgrade pipenv
        # deploy ensures packages are properly locked in Pipfile.lock, and aborts if the lock file is out-of-date
        pipenv install --deploy 
    - name: Test with pytest
      run: |
        pipenv run pytest --cov-report term
