name: pyimp-yaml
on: [push]
jobs:
  install:
    steps:
      - name: install dependencies
        runs-on: ubuntu-latest
        run: |
          pip3 install pipenv
          pipenv shell
          pipenv install
      - name: run main
        run: pipenv run python main.py
